Add Bluesky Bot(s). (Readme already made)
Tolga1452/ai-prompts pull request #1
Opened 2024-11-27 17:09 UTC by lu2000luk

Since Discord Bots are added and i own a open source AI bot on bluesky i felt like something was missing.

2024-11-29 20:31 UTC, Tolga1452 requested changes
Thank you for your contribution! I requested a few little changes and then your PR is ready!

2024-11-29 20:31 UTC, Tolga1452 commented on README.md
> +- [Bluesky Bot](https://github.com/Tolga1452/ai-prompts/tree/main/Bluesky%20Bot)
```suggestion
```

All the categories are in the alphabet order. Can you please move it under "Apple Intelligence"?

2024-11-29 20:31 UTC, Tolga1452 commented on README.md
> +- **RuttoniSky:** [lu2000luk/RuttoniSky](https://github.com/lu2000luk/RuttoniSky)
```suggestion
- **Apple Intelligence:** [Explosion-Scratch/apple-intelligence-prompts](https://github.com/Explosion-Scratch/apple-intelligence-prompts)
- **RuttoniSky:** [lu2000luk/RuttoniSky](https://github.com/lu2000luk/RuttoniSky)
- **bolt.new:** [stackblitz/bolt.new](https://github.com/stackblitz/bolt.new)
- **Microsoft Copilot:** [wunderwuzzi23/scratch](https://github.com/wunderwuzzi23/scratch)
```
Let's move this one too.

2024-12-01 09:50 UTC, lu2000luk commented
Sure, once i get back home (in a few days, ill fix it)

2025-08-24 03:08 UTC, closed without merging